import pathlib

MODULES_DIR = pathlib.Path(__file__).resolve().parent
ROOT_DIR = MODULES_DIR.parent

MODULE_PASSWORD_COMP_DIR = MODULES_DIR / "password_comp"
MODULE_PASSWORD_COMP_API = MODULE_PASSWORD_COMP_DIR / "api.py"
MODULE_PASSWORD_COMP_ROCKYOU = MODULE_PASSWORD_COMP_DIR / "rockyou.py"
MODULE_PASSWORD_COMP_SMTP = MODULE_PASSWORD_COMP_DIR / "smpt.py"

DATA_DIR = ROOT_DIR / "data"
DATA_ROCKYOU_DIR = DATA_DIR / "rockyou"
DATA_ROCKYOU_HASH_CSV = DATA_ROCKYOU_DIR / "hash_comp.csv"